version: "3.8"
services:
  app:
    build: .
    container_name: employee_app
    ports:
      - "8080:8080"
    environment:
      SPRING_H2_CONSOLE_ENABLED: "true"
      SPRING_H2_CONSOLE_PATH: "/h2-console"
      SPRING_H2_CONSOLE_SETTINGS_WEB_ALLOW_OTHERS: "true"
